version: "3.9"

services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: vectordb
      POSTGRES_USER: vectoruser
      POSTGRES_PASSWORD: vectorpass

    volumes:
      - pgvector_data:/var/lib/postgresql/data

    shm_size: 1gb


  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-ui
    restart: unless-stopped

    ports:
      - "5050:80"

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    depends_on:
      - pgvector


volumes:
  pgvector_data:



# export POSTGRES_DSN="postgres://vectoruser:vectorpass@localhost:5432/vectordb?sslmode=disable"3